/*
 * exec-hook.c bash fixes on plain Linux (run with the reroute hook, i.e.
 * LINKER=fake-linker, see tests/run-local.sh):
 *
 *   A. execve("/bin/bash", ...) — dsh's PTY shell spawn — must be rewritten
 *      to $DSH_FILES_DIR/usr/bin/bash (the wrapper) with the original argv
 *      preserved, even though the child envp lacks the DSH_* variables the
 *      wrapper needs (dsh scrubs them).
 *   B. execve($DSH_FILES_DIR/usr/bin/bash, ...) — the one-shot PATH-resolved
 *      wrapper case — must re-inject DSH_FILES_DIR/DSH_WORKSPACE into the
 *      child environment.
 *
 * The fake linker (fake-linker, generated by run-local.sh) validates argv
 * and the injected env and exits 0 only when both hold; its output is
 * captured so a silent fall-through to a host /bin/bash can never fake a
 * pass. This process sets DSH_FILES_DIR/DSH_WORKSPACE in its own environment
 * (as the engine does) but passes a scrubbed envp to execve (as dsh does).
 */
#include <assert.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>

static int run_captured(const char *path, char *const argv[],
                        char *const envp[], char *out, size_t outsz) {
  int fds[2];
  if (pipe(fds) != 0) return -1;
  pid_t pid = fork();
  if (pid == 0) {
    dup2(fds[1], 1);
    dup2(fds[1], 2);
    close(fds[0]);
    close(fds[1]);
    int nullfd = open("/dev/null", O_RDONLY);
    if (nullfd >= 0) {
      dup2(nullfd, 0);
      close(nullfd);
    }
    execve(path, argv, envp);
    _exit(127);
  }
  close(fds[1]);
  ssize_t n = read(fds[0], out, outsz - 1);
  if (n < 0) n = 0;
  out[n] = '\0';
  close(fds[0]);
  int status = 0;
  waitpid(pid, &status, 0);
  if (!WIFEXITED(status)) return -1;
  return WEXITSTATUS(status);
}

int main(void) {
  const char *files = getenv("DSH_FILES_DIR");
  const char *workspace = getenv("DSH_WORKSPACE");
  assert(files && *files && "DSH_FILES_DIR must be set by the runner");
  assert(workspace && *workspace && "DSH_WORKSPACE must be set by the runner");

  char wrapper[4096];
  int n = snprintf(wrapper, sizeof wrapper, "%s/usr/bin/bash", files);
  assert(n > 0 && (size_t)n < sizeof wrapper);

  /* A. PTY shell spawn: absolute /bin/bash, scrubbed child envp. */
  {
    char *const argv[] = {"/bin/bash", "--noprofile", "--norc", "-i", NULL};
    char *const envp[] = {"PATH=/usr/bin:/system/bin", NULL};
    char out[256] = {0};
    int rc = run_captured("/bin/bash", argv, envp, out, sizeof out);
    assert(rc == 0 && "rewritten /bin/bash must reach the fake linker");
    assert(strstr(out, "rewrite-ok") &&
           "argv must be preserved and DSH_* env re-injected");
  }

  /* B. One-shot wrapper exec (PATH-resolved "bash"): the engine execs the
   * resolved wrapper path with argv[0] still "bash"; env must be injected. */
  {
    char *const argv[] = {"bash", "-c", "echo hi", NULL};
    char *const envp[] = {"PATH=/usr/bin:/system/bin", NULL};
    char out[256] = {0};
    int rc = run_captured(wrapper, argv, envp, out, sizeof out);
    assert(rc == 0 && "wrapper exec must reach the fake linker");
    assert(strstr(out, "env-ok") &&
           "DSH_FILES_DIR/DSH_WORKSPACE must be injected into the wrapper");
  }

  printf("bash-fix tests passed\n");
  return 0;
}